"""Unit tests for the gRPC servicer."""

from __future__ import annotations

import importlib
import sys
from types import ModuleType
from unittest.mock import MagicMock, patch


def _build_fake_pb2_modules() -> tuple[ModuleType, ModuleType]:
    """Create lightweight protobuf stand-ins used by main_grpc in tests."""
    pb2 = ModuleType("nlp_service_pb2")

    class AnalyzeRequest:
        def __init__(
            self,
            text: str = "",
            categories: list[str] | None = None,
            tonalities: list[str] | None = None,
        ) -> None:
            self.text = text
            self.categories = categories or []
            self.tonalities = tonalities or []

    class CategoryScore:
        def __init__(self, category: str, score: float) -> None:
            self.category = category
            self.score = score

    class TonalityScore:
        def __init__(self, tonality: str, score: float) -> None:
            self.tonality = tonality
            self.score = score

    class AnalyzeResponse:
        def __init__(
            self,
            language: str,
            sentiment: str,
            sentiment_score: float,
            matched_categories: list[CategoryScore],
            matched_tonalities: list[TonalityScore],
            is_toxic: bool,
            highest_toxicity_score: float,
            processing_time_ms: float,
        ) -> None:
            self.language = language
            self.sentiment = sentiment
            self.sentiment_score = sentiment_score
            self.matched_categories = matched_categories
            self.matched_tonalities = matched_tonalities
            self.is_toxic = is_toxic
            self.highest_toxicity_score = highest_toxicity_score
            self.processing_time_ms = processing_time_ms

    class AnalyzeBatchRequest:
        def __init__(
            self,
            texts: list[str] | None = None,
            categories: list[str] | None = None,
            tonalities: list[str] | None = None,
        ) -> None:
            self.texts = texts or []
            self.categories = categories or []
            self.tonalities = tonalities or []

    class AnalyzeBatchResponse:
        def __init__(self, results: list[AnalyzeResponse]) -> None:
            self.results = results

    pb2.AnalyzeRequest = AnalyzeRequest
    pb2.CategoryScore = CategoryScore
    pb2.TonalityScore = TonalityScore
    pb2.AnalyzeResponse = AnalyzeResponse
    pb2.AnalyzeBatchRequest = AnalyzeBatchRequest
    pb2.AnalyzeBatchResponse = AnalyzeBatchResponse

    pb2_grpc = ModuleType("nlp_service_pb2_grpc")

    class NlpServiceServicer:
        """Base class stand-in generated by grpcio-tools."""

    pb2_grpc.NlpServiceServicer = NlpServiceServicer
    pb2_grpc.add_NlpServiceServicer_to_server = lambda *_args, **_kwargs: None

    return pb2, pb2_grpc


_PB2, _PB2_GRPC = _build_fake_pb2_modules()
sys.modules.setdefault("nlp_service_pb2", _PB2)
sys.modules.setdefault("nlp_service_pb2_grpc", _PB2_GRPC)
sys.modules.pop("main_grpc", None)
MAIN_GRPC = importlib.import_module("main_grpc")


def test_grpc_analyze_maps_engine_output() -> None:
    """Analyze RPC maps engine output to protobuf response fields."""
    engine = MagicMock()
    engine.analyze.return_value = {
        "language": "en",
        "sentiment": "positive",
        "sentiment_score": 0.91,
        "matched_categories": [
            {"category": "technology", "score": 0.83},
            {"category": "science", "score": 0.74},
        ],
        "matched_tonalities": [
            {"tonality": "formal", "score": 0.88},
            {"tonality": "objective", "score": 0.76},
        ],
        "is_toxic": False,
        "highest_toxicity_score": 0.07,
        "processing_time_ms": 10.0,
    }

    servicer = MAIN_GRPC.NlpServiceServicer(engine)
    request = _PB2.AnalyzeRequest(
        text="AI is changing the world.",
        categories=["technology", "science"],
        tonalities=["formal", "objective"],
    )

    response = servicer.Analyze(request, MagicMock())

    engine.analyze.assert_called_once_with(
        "AI is changing the world.",
        ["technology", "science"],
        ["formal", "objective"],
    )
    assert response.language == "en"
    assert response.sentiment == "positive"
    assert response.sentiment_score == 0.91
    assert len(response.matched_categories) == 2
    assert response.matched_categories[0].category == "technology"
    assert len(response.matched_tonalities) == 2
    assert response.matched_tonalities[0].tonality == "formal"
    assert response.is_toxic is False
    assert response.highest_toxicity_score == 0.07
    assert response.processing_time_ms >= 0


def test_grpc_analyze_alias_calls_handler() -> None:
    """The generated-style Analyze alias should invoke analyze logic."""
    engine = MagicMock()
    engine.analyze.return_value = {
        "language": "de",
        "sentiment": "neutral",
        "sentiment_score": 0.52,
        "matched_categories": [],
        "matched_tonalities": [],
        "is_toxic": False,
        "highest_toxicity_score": 0.02,
        "processing_time_ms": 8.0,
    }

    servicer = MAIN_GRPC.NlpServiceServicer(engine)
    request = _PB2.AnalyzeRequest(text="Hallo Welt")

    response = servicer.Analyze(request, MagicMock())

    engine.analyze.assert_called_once_with("Hallo Welt", [], [])
    assert response.language == "de"
    assert response.sentiment == "neutral"
    assert response.matched_categories == []
    assert response.matched_tonalities == []


def test_grpc_analyze_batch_maps_engine_output() -> None:
    """AnalyzeBatch RPC maps batch results correctly."""
    engine = MagicMock()
    engine.analyze_batch.return_value = [
        {
            "language": "en",
            "sentiment": "positive",
            "sentiment_score": 0.88,
            "matched_categories": [{"category": "tech", "score": 0.9}],
            "matched_tonalities": [{"tonality": "formal", "score": 0.72}],
            "is_toxic": False,
            "highest_toxicity_score": 0.09,
            "processing_time_ms": 30.0,
        },
        {
            "language": "fr",
            "sentiment": "negative",
            "sentiment_score": 0.81,
            "matched_categories": [{"category": "politics", "score": 0.64}],
            "matched_tonalities": [{"tonality": "aggressive", "score": 0.77}],
            "is_toxic": True,
            "highest_toxicity_score": 0.92,
            "processing_time_ms": 33.0,
        },
    ]

    servicer = MAIN_GRPC.NlpServiceServicer(engine)
    request = _PB2.AnalyzeBatchRequest(
        texts=["AI is useful.", "Je te deteste."],
        categories=["tech", "politics"],
        tonalities=["formal", "aggressive"],
    )

    response = servicer.AnalyzeBatch(request, MagicMock())

    engine.analyze_batch.assert_called_once_with(
        ["AI is useful.", "Je te deteste."],
        ["tech", "politics"],
        ["formal", "aggressive"],
    )
    assert len(response.results) == 2
    assert response.results[0].language == "en"
    assert response.results[1].is_toxic is True


def test_grpc_serve_starts_server() -> None:
    """serve() should initialize telemetry/instrumentation and start the gRPC server."""
    server = MagicMock()

    with (
        patch.object(MAIN_GRPC, "setup_logging") as setup_logging_mock,
        patch.object(MAIN_GRPC, "setup_telemetry") as setup_telemetry_mock,
        patch.object(MAIN_GRPC.nltk, "download") as nltk_download_mock,
        patch.object(MAIN_GRPC, "NlpEngine", return_value=MagicMock()) as engine_cls,
        patch.object(MAIN_GRPC, "GrpcInstrumentorServer") as instrumentor_cls,
        patch.object(MAIN_GRPC.grpc, "server", return_value=server),
        patch.object(MAIN_GRPC.nlp_service_pb2_grpc, "add_NlpServiceServicer_to_server") as add_srv,
    ):
        instrumentor_cls.return_value.instrument.return_value = None
        server.add_insecure_port.return_value = 50051
        server.wait_for_termination.return_value = None

        MAIN_GRPC.serve()

    setup_logging_mock.assert_called_once()
    setup_telemetry_mock.assert_called_once()
    nltk_download_mock.assert_called_once_with("punkt_tab", quiet=True)
    engine_cls.assert_called_once()
    instrumentor_cls.return_value.instrument.assert_called_once()
    add_srv.assert_called_once()
    server.start.assert_called_once()
    server.wait_for_termination.assert_called_once()
